### ISSUE TITLE
Allianz

### ISSUE THREAD

**Issue by hansimglueck** [hansimglueck/homeVisit#11]
"V O R L E S E N: Jetzt haben die beiden am besten Platzierten die Möglichkeit, eine Allianz zu schließen. Diese Allianz funktioniert so: Die beiden Teams geben sich gegenseitig keine Minuspunkte mehr, werden dann aber auch als Bestplatzierte sichtbar."

**Comment by hansimglueck** [comment]
es gibt nun das item, aber die logik noch nicht (geschlossenen allianzen haben keinen einfluss auf die teams)

**Comment by gritschu** [comment]
Es wäre außerdem gut, wenn parallel die anderen Spieler auch etwas auf ihren Screen kriegten und was zu tun haben, damit die beiden Bestplatzierten nicht sofort auffliegen.

Regie-Vorschlag:
Die anderen bekommen eine interessante Info daüber wer die beiden besten in Europa in puncto Export von XY sind. Oder so. - DW

**Comment by hansimglueck** [comment]
die anderen müssen per follow-Item eine karte mit beliebiger info bekommen -> device = player:!topTwo
