### ISSUE TITLE
Minuspunkte offenlegen - nur das schlechteste Team

### ISSUE THREAD

**Issue by jannphilipparnold** [hansimglueck/homeVisit#112]
Die Spieler haben die Option abzustimmen, ob keiner, alle oder nur das am schlechtesten bewertete Team ihre gegebenen Minuspunkte offenlegen sollen (Deck: Nummer 118). Bis jetzt können aber nur die Minuspunkte von allen Spielern offengelegt werden (mit dem ShowAssholes Item) oder man kann auf die nächste Karte springen und somit gar keine Minuspunkte anzeigen. Es ist also nicht möglich, einfach nur die gegebenen Minuspunkte des schlechtesten Teams anzuzeigen.

**Comment by hansimglueck** [comment]
kann jetzt als option im asshole-item ausgewählt werden
