### ISSUE TITLE
Zeitbegrenzung für Bewertungen & Deals

### ISSUE THREAD

**Issue by jannphilipparnold** [hansimglueck/homeVisit#119]
Für Bewertungen und Deals soll es Zeitbegrenzungen geben, so wie es sie schon für Abstimmungen gibt. D.h., dass man eine Zeitgrenze von z.B. 40 Sekunden setzen kann, wovon in den letzten 12 Sekunden der Download startet. Danach wird dann direkt in die nächste Karte gesprungen.

**Comment by buzz** [comment]
dup: #110
