### ISSUE TITLE
Auschluss Button für MC

### ISSUE THREAD

**Issue by jannphilipparnold** [hansimglueck/homeVisit#120]
Gewünscht ist ein Button im MC Interface, mit dem der Spielleiter eines der Teams während des Spiels ausschließen kann. Bis jetzt ist es so, dass das Team ihr Handy an den MC abgeben muss sollte es ausgeschlossen werden, und der MC das Handy dann ausschaltet bevor es weitergeht. Mit dem Button soll es möglich gemacht werden, dass das Team einfach als Teilnehmer verschwindet, und dass dieses herausgeworfene Team am Ende auch nicht in der Kuchenverteilung auftritt.

**Comment by hansimglueck** [comment]
yo. läuft. team-details-throw out
