### ISSUE TITLE
Bestenallianz: Minuspunkte

### ISSUE THREAD

**Issue by jannphilipparnold** [hansimglueck/homeVisit#121]
Wenn die besten Teams die Allianz eingehen, sollen diese beide je einen Punkt als Kosten für die Allianz verlieren. So wird das auch in der Karte davor beschrieben. Bis jetzt passiert aber nichts, und bei Abschluss einer solchen Allianz geht es einfach ohne Punkteverlust weiter.

**Comment by hansimglueck** [comment]
punkte werden jetzt abgezogen. alliierte werden im score-barometer für jeden mit afrben dargestellt
