### ISSUE TITLE
Absätze auf Handy-Karten

### ISSUE THREAD

**Issue by jannphilipparnold** [hansimglueck/homeVisit#123]
Wenn man im Admin bei Karten, die auf die Handys geleitet werden, Absätze setzt, erscheinen diese nicht auf den Screens, sondern werden einfach nur zu einem einzelnen Leerzeichen gemacht. Stiftet bei manchen Karten Verwirrung.

**Comment by hansimglueck** [comment]
<br /> macht nen absatz und andere html-tags können auch verwendet werden
