### ISSUE TITLE
MC-playback positionen checken

### ISSUE THREAD

**Issue by hansimglueck** [hansimglueck/homeVisit#130]
manchmal ist die aktuelle karte nicht in der mitte oder so

**Comment by buzz** [comment]
würd ich mir gern angucken, aber wie reproduziere ich das? ist mir noch nie untergekommen...

**Comment by gritschu** [comment]
Ich habe auch noch kein Muster erkannt, vielleicht mal Philipp ansetzen, dass er schaut, ob es immer nur in bestimmten Szenen auftaucht?

**Comment by buzz** [comment]
hab jetzt beim testen nochmal drauf geachtete und auch den mc gefragt und das problem scheint  zumindest momentan nicht aufzutreten.
