### ISSUE TITLE
Tortendiagramme: Doppelpunkte raus!

### ISSUE THREAD

**Issue by jannphilipparnold** [hansimglueck/homeVisit#134]
Bei Results (Tortendiagrammen) sollen keine Doppelpunkte vor den Prozentzahlen stehen. Derweil steht da immer noch, z.B.: "234 € pro Jahr.: XX.XX % (2 Teams)". Das ist aber grammatikalisch falsch, und sollte heißen: "234 € pro Jahr. XX.XX % (2 Teams)", also ohne doppelte Zeichensetzung.

Zudem gibt es die Anfrage von Katja, die Legende zu den Diagrammen weiter nach links zu rücken, um somit längere Antwortmöglichkeiten zu haben (und daher mehr von der Antwort lesen zu können --> mehr Zeichen).

**Comment by hansimglueck** [comment]
ist umgesetzt
