### ISSUE TITLE
Minuspunkte statt Pluspunkte verteilt

### ISSUE THREAD

**Issue by jannphilipparnold** [hansimglueck/homeVisit#136]
Es geht speziell um Karte 122 im Strang. Die Spieler haben die Chance, zwei Punkte zu kriegen, wenn sie beim Abwaschen helfen; das schnellste Team gewinnt.

Gerade beim Durchspielen hat der Spieler, der gewonnen hat, allerdings 2 Minuspunkte statt Pluspunkte erhalten. Sollte ich weiterleiten!

**Comment by hansimglueck** [comment]
wenn ich mich recht entsinne lags an der falschen option im strang...
