### ISSUE TITLE
Team flags setzen können (an/abwesend/selected/dran)

### ISSUE THREAD

**Issue by buzz** [hansimglueck/homeVisit#17]
* Teams ab/anwesend stellen
* das von den anderen Teams ausgewählte Team selektieren (so dass ich habe genug-button an allbutselected gehen kann)
* Team dran stellen

**Comment by gritschu** [comment]
- Teams abwesend / anwesend stellen --- done (property away)
- Team selektieren / deselektieren --- done (property selected) ---> player:allButSelected funktioniert auch

**Comment by gritschu** [comment]
- upcoming Team wird im MC angezeigt und kann jetzt dort gesetzt werden, 
Commit: 6fcbbb707d3a69d97781aee764c95510d150ffb7
