### ISSUE TITLE
Cruft löschen

### ISSUE THREAD

**Issue by buzz** [hansimglueck/homeVisit#20]
ungenutzten/obsoleten/alten kram/dateien aus dem code löschen

**Comment by hansimglueck** [comment]
Habe meinen Teil dazu erstmal getan:

e7fa1c95fe564bdf7263ee31f0269b44f5814950
4f92145835fd418a148eb23940ab09ab0a2a9afd
ad81ce5cffe45cbf95e85e2b78504d85513d8f44

**Comment by buzz** [comment]
6e3fb5caa1085e2f922499b174ee3b3caaa2e52b
ce18f613021affab7205a32251ed8d45e2aaff5c
ae0da38852de7264bc0206c63f456f858ad49083
soweit sogut...
