### ISSUE TITLE
import/export JSON per SequenceItem

### ISSUE THREAD

**Issue by buzz** [hansimglueck/homeVisit#27]
Jedes SequenceItem (möglichst auch inline) sollten 2 zusätzliche buttons bekommen: Import JSON und Export JSON.
So lassen sich Items bequem in die Zwischenablage kopieren.

**Comment by buzz** [comment]
86661d93d60f279e9bc67a99cedee432a7b7685c

**Comment by hansimglueck** [comment]
brauchen wir nit
