### ISSUE TITLE
Mehrfache Deals

### ISSUE THREAD

**Issue by jannphilipparnold** [hansimglueck/homeVisit#33]
Ein Spieler kann zwei Anfragen für Deals kriegen:

Wenn man einen zweiten annimmt, wird der erste aufgelöst

**Comment by gritschu** [comment]
Wenn Team einen Deal abgeschlossen hat, sollte es keine neue Anfrage mehr bekommen können, ergo auf dem Teamauswahlscreen der anderen nicht mehr aufgelistet sein.
