### ISSUE TITLE
Roulette: Spieler-Einbeziehung (Rego-Problem?)

### ISSUE THREAD

**Issue by gritschu** [hansimglueck/homeVisit#39]
Beim Tryout wurden nicht alle Spieler, die mitspielen gedrückt hatten, ins Spiel einbezogen.
Das könnte ein Rego-Problem gewesen sein.

**Comment by hansimglueck** [comment]
oder auch ein zuoft hin und her gedrückt problem. bitte wiederaufmachen, wenn systematisch
