### ISSUE TITLE
Minuspunkte-Tracker

### ISSUE THREAD

**Issue by gritschu** [hansimglueck/homeVisit#40]
- System muss sich merken, an wen die Spieler Minuspunkte verteilen.
- System muss anzeigen können, wer an wen die meisten Minuspunkte verteilt hat.

FRAGE GEKLÄRT:
Es soll bei jedem Team angezeigt werden, von wem man die meisten Minuspunkte bekommen hat.

**Comment by hansimglueck** [comment]
plan 0: event-log-modal mit filter versehen, sodass man nur vergebene -punkte sieht...

**Comment by hansimglueck** [comment]
plan 1. asshole-item machts. (zeigt im moment alle minuspunkte an...)
