### ISSUE TITLE
Zahleingabeauswertung Layout

### ISSUE THREAD

**Issue by gritschu** [hansimglueck/homeVisit#42]
Zwischen Gesamtergebnis und "Durchschnitt" sollte zumindest ein Abstand sein.
Ggf. nochmal eigene Eingabe anzeigen?

So sieht es im Moment aus:
"Gesamt: 30Durchschnitt: 15.00"

**Comment by hansimglueck** [comment]
ist erstmal mehrzeilig. 
rest fällt unter allg. hübsch machen
