### ISSUE TITLE
Punktvergabe an ein Team: Punkteverteilfehler, anscheinend zufällig

### ISSUE THREAD

**Issue by gritschu** [hansimglueck/homeVisit#49]
Anscheinend: Wenn Teams einem anderen Team einen Pluspunkt geben, landet der Punkt manchmal bei irgend einem anderem.
Noch kein Muster erkannt. Außer dass es so aussieht, als würde bei Minuspunktvergabe alles korrekt funktionieren, bei Pluspunktvergabe aber nicht.

**Comment by hansimglueck** [comment]
@jannphilipparnold: kannst du das reproduzieren?
