### ISSUE TITLE
Abstimmung vom MC/Admin übersprungen --> Countdown wird trotzdem getriggert

### ISSUE THREAD

**Issue by gritschu** [hansimglueck/homeVisit#50]
Abstimmung wurde (aus welchem Grund auch immer) geskippt --> im nächsten Step kommt dann trotzdem noch der Countdown. Der sollte aber eigentlich gar nicht mehr aktiviert werden.

**Comment by hansimglueck** [comment]
sollte jetzt funktionieren...
@jannphilipparnold bestätigt? dann bitte close

**Comment by jannphilipparnold** [comment]
Problem tritt leider immer noch auf... @hansimglueck

**Comment by hansimglueck** [comment]
habs ja jetzt auch erst gepusht. bei weiteren problem bitte re-open
