### ISSUE TITLE
Rego bei Abstimmungen: Punkte resetten

### ISSUE THREAD

**Issue by gritschu** [hansimglueck/homeVisit#52]
Wenn (aus welchem Grund auch immer) eine Abstimmung unterbrochen und dann nochmals aufgerufen wird, sollten die Teams, die beim ersten Mal ihre Option schon eingeloggt hatten, nicht 2x ausgewertet werden.

**Comment by hansimglueck** [comment]
wird nur nochmal vergeben, wenn die abstimmung nochmal durchgeführt wird 
(rego auf result) oder nochmal back zur abstimmung, wenn result schon war. DAS muss verhindert werden...
