### ISSUE TITLE
Schätzung des Geldes ---> Später Punkte für richtige Schätzung

### ISSUE THREAD

**Issue by gritschu** [hansimglueck/homeVisit#53]
An einer Stelle im Spiel sollen die Teams eine Schätzung über ihr Bargeld im Verlgeich zum Durchschnitt aller abgeben. Später wird der Durchschnitt berechnet. Daraufhin sollen die Teams aufgrund ihrer abgegebenen Schätzung entsprechend plus- oder Minuspunkte bekommen.

**Comment by hansimglueck** [comment]
lässt sich am sinnigsten per eval-item implementieren. folgt coch

**Comment by hansimglueck** [comment]
läuft schon
