### ISSUE TITLE
Player: Bestplatzierter wird verraten

### ISSUE THREAD

**Issue by gritschu** [hansimglueck/homeVisit#60]
Genauer Ablauf wird besprochen.
Bisher:
V O R L E S E N: Wer will 2 Punkte einsetzen um zu erfahren, welches Team auf Platz eins ist! - - Auf Display von PLatz 1 erscheint: Benehmt Euch unauffällig. Die anderen bekommen angeboten, 2 Punkte zu bezahlen, um zu erfahren, wer auf Platz 1 ist. 

x ---- neue Vorschlag DW: Auf Display von PLatz 1 erscheint: Benehmt Euch unauffällig. Die anderen bekommen angeboten, 2 Punkte zu bezahlen, um zu erfahren, wer auf Platz 1 ist. 

Frage an Regie:
Wird bei jedem, der das will, das Siegerteam angezeigt
ODER
SAGT der Spielleiter denjenigen (flüstert ins Ohr), wer das bestplatzierte Team ist?

**Comment by hansimglueck** [comment]
ist scheinbar überholt
