### ISSUE TITLE
Player: Am schnellsten "Ich will" antippen

### ISSUE THREAD

**Issue by gritschu** [hansimglueck/homeVisit#61]
V O R L E S E N: Wer will 2 Punkte verdienen, in dem das Team sich jetzt bereit erklärt nach dem Spiel zu helfen den Tisch abzuräumen und abzuwaschen? Wer am schnellsten tippt, bekommt den Zuschlag. 3-2-1- go!

Button: Wir helfen, bis zum Ende - ehrlich! 
Wer als erstes getippt hat, bekommt den Zuschlag. Spielleiter muss sehen, wer das ist, damit er sicherstellen kann, dass die dann auch wirklich helfen. ;)

**Comment by hansimglueck** [comment]
sollte wie gebastelt funktionieren. countdown sollte auch gecancellt werden?
