### ISSUE TITLE
Mehrere selektierte Teams bepunkten

### ISSUE THREAD

**Issue by jannphilipparnold** [hansimglueck/homeVisit#62]
Wenn der MC mehrere Teams selektiert (bei: "Entscheidet euch, ob ihr den Teams der beiden Spieler, die vorhin aus dem Fenster gerufen haben, einen Punkt dafür geben oder einen abziehen wollt."), dann wird im Playerscreen nur eins von den beiden Teams angezeigt. Es sollten aber beide sein, und beide sollten auch jeweils den Punkt bekommen.

**Comment by hansimglueck** [comment]
sollte in 2076c28 behoben sein
