### ISSUE TITLE
Überspringen von Items ja nach Zeitnot

### ISSUE THREAD

**Issue by gritschu** [hansimglueck/homeVisit#72]
Zwei Aternativen stehen zur Wahl:

- Fest definierte Jump Points --> Bei Zeitnot werden alle noch kommenden Items bis zu diesem Jump Point übersprungen

- Prioritäten für Items --> Bei Zeitnot werden Low-Prio-Items ausgeschaltet und werden automatisch übersprungen

**Comment by hansimglueck** [comment]
sound stoppen
alle konfig-items ausführen
