### ISSUE TITLE
Player + MC: Der am schnellsten gedrückt hat - anzeigen

### ISSUE THREAD

**Issue by gritschu** [hansimglueck/homeVisit#77]
An der Stelle, wo gefragt wird, wer aufräumen hilft und dafür belohnt wird, soll allen angezeigt werden, wer den Zuschlag bekommen hat.
Auch der MC soll das sehen.

**Comment by hansimglueck** [comment]
der player kriegts angezeigt, der mc soll ja eh noch die ergebnisse bekommen...
