### ISSUE TITLE
Kuchenaufteilungsausdruck mit Farbinfo

### ISSUE THREAD

**Issue by gritschu** [hansimglueck/homeVisit#79]
Farbe der Teams mit ausdrucken

- Die Farbbegriffe sollten lokalisiert an den Printer_client geschickt werden, damit dieser sie dann auch ausdrucken kann

--> Danach bitte wieder an Grit zurück assignen.

**Comment by gritschu** [comment]
Farbnamen kommen unlokalisiert an und werden ausgedruckt

**Comment by hansimglueck** [comment]
sollte jetzt so sein
