### ISSUE TITLE
Versicherung

### ISSUE THREAD

**Issue by hansimglueck** [hansimglueck/homeVisit#8]
konfigurierbare schrittzahl:
erster schritt nur anfragen, letzter schritt nur ja/nein

nur einen deal abschliessen können

bedienung intuitiver gestalten

sound bei "geht los"

**Comment by gritschu** [comment]
- Wenn Deal abgeschlossen, diese beiden Dealpartner sollen keine neuen Deal-Anfragen mehr bekommen können. (Raus aus der Auswahlansicht der anderen.)
- Bug: Deal wurde denied --> Team kam nicht mehr zur Deal-Partnerauswahl zurück
- Bug: Deal-Screen wurde im Anschluss im Spielverlauf immer wieder auf den Player-Displays angezeigt

**Comment by jannphilipparnold** [comment]
- Zwei Teams sind miteinander versichert. Das besser platzierte soll einen Pluspunkt bekommen. Nun war es so, dass bei der Punktvergabe dieses Team einen Minuspunkt bekam – weil es weiter als 3 Punkte vom Versicherungspartner entfernt war. Es müsste aber der vergebene Punkt stattdessen an den schlechter platzierten Versicherungspartner gehen.

**Comment by hansimglueck** [comment]
hoffe, der ist wirklich schliessenswert
